import { HttpClient, HttpContext, HttpParams } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { environment } from '../../../environments/environment';
import { CompanyHolidayCreateRequest, CompanyHolidayDto, GenerateCompanyHolidaysResult } from '../models/company-holiday.model';
import { SUPPRESS_ERROR_TOAST } from '../http/http-context.tokens';

/** Non-working days for one Company - nested under /api/companies/{companyId}/holidays,
 * not a standalone šifrarnik (no paging, list is filtered by year instead), so
 * this doesn't extend PagedCrudService. Feeds the location form dialog's
 * "Praznici" tab (see CompanyHolidaysTabComponent). */
@Injectable({ providedIn: 'root' })
export class CompanyHolidaysService {
  private readonly baseUrl = `${environment.apiUrl}/api/companies`;

  constructor(private readonly http: HttpClient) {}

  getForYear(companyId: string, year: number): Observable<CompanyHolidayDto[]> {
    const params = new HttpParams().set('year', year);
    return this.http.get<CompanyHolidayDto[]>(`${this.baseUrl}/${companyId}/holidays`, { params });
  }

  /** Always isAutoGenerated:false - manual entry, used for moveable feast days
   * the generator excludes and for countries it doesn't cover at all. */
  create(
    companyId: string,
    request: CompanyHolidayCreateRequest,
    options?: { suppressErrorToast?: boolean },
  ): Observable<CompanyHolidayDto> {
    return this.http.post<CompanyHolidayDto>(`${this.baseUrl}/${companyId}/holidays`, request, {
      context: new HttpContext().set(SUPPRESS_ERROR_TOAST, options?.suppressErrorToast ?? false),
    });
  }

  delete(companyId: string, id: string): Observable<void> {
    return this.http.delete<void>(`${this.baseUrl}/${companyId}/holidays/${id}`);
  }

  /** Tries an external catalog first, falls back to a built-in HR list; may
   * reject with 409 HOLIDAY_CATALOG_NOT_DEFINED_FOR_COUNTRY for an
   * unsupported country - always suppress the toast and handle that code
   * inline (see CompanyHolidaysTabComponent.onGenerate). */
  generate(
    companyId: string,
    year: number,
    options?: { suppressErrorToast?: boolean },
  ): Observable<GenerateCompanyHolidaysResult> {
    const params = new HttpParams().set('year', year);
    return this.http.post<GenerateCompanyHolidaysResult>(`${this.baseUrl}/${companyId}/holidays/generate`, null, {
      params,
      context: new HttpContext().set(SUPPRESS_ERROR_TOAST, options?.suppressErrorToast ?? false),
    });
  }
}
