/** One non-working day for a Company/location - blocks scheduling that day and
 * is silently skipped when generating group appointments (backend concern,
 * already live; this frontend only reads/writes the catalog). Row shape of
 * GET .../holidays and the `created` array of GenerateCompanyHolidaysResult. */
export interface CompanyHolidayDto {
  id: string;
  companyId: string;
  companyName: string;
  date: string;
  name: string;
  /** false for anything created via POST .../holidays (manual entry, or a
   * moveable feast like Uskrs the auto-generator deliberately excludes) - true
   * only for a row created by POST .../holidays/generate. */
  isAutoGenerated: boolean;
  createdAt: string;
  createdBy?: string;
}

/** Body for POST /api/companies/{companyId}/holidays - always produces an
 * isAutoGenerated:false row, whether that's a genuinely manual holiday or a
 * country the auto-generator doesn't cover. */
export interface CompanyHolidayCreateRequest {
  date: string;
  name: string;
}

/** Response of POST /api/companies/{companyId}/holidays/generate?year=. Tries
 * an external catalog first, falls back to a built-in HR list; other
 * countries with neither available get a 409 HOLIDAY_CATALOG_NOT_DEFINED_FOR_COUNTRY
 * instead of this shape. */
export interface GenerateCompanyHolidaysResult {
  createdCount: number;
  skippedCount: number;
  created: CompanyHolidayDto[];
}
