/** GET /api/products/{id} and the items of its paged list. Product is
 * organization-level (not Company-specific) - stock per Company lives
 * separately in ProductStockDto. */
export interface ProductDto {
  id: string;
  name: string;
  description?: string;
  sku?: string;
  defaultPrice: number;
  isActive: boolean;
  createdAt: string;
  createdBy?: string;
  updatedAt?: string;
  updatedBy?: string;
}

/** Body for both POST /api/products and PUT /api/products/{id} - the two
 * requests are identical; `isActive` is never sent, it has its own
 * activate/deactivate endpoints. SKU is optional but, when present, must stay
 * globally unique within the Organization regardless of active status
 * (DUPLICATE_SKU) - the backend remains authoritative. */
export interface ProductUpsertRequest {
  name: string;
  description: string | null;
  sku: string | null;
  defaultPrice: number;
}

/** GET /api/stock/company/{companyId} - current stock of every product at one
 * company. A product with no matching row here has zero stock (no row is
 * ever created until the first adjustment) - never hide a product from a
 * picker/list just because it has no stock row, show "0" instead. */
export interface ProductStockDto {
  productId: string;
  productName: string;
  companyId: string;
  companyName: string;
  quantity: number;
  updatedAt: string;
}

/** Mirrors the backend's StockMovementType enum (Enums/StockMovementType.cs) -
 * the sole source of truth for stock change history. SaleReversal is reserved
 * for a future refund flow and is never generated by any current code path,
 * but is included here so an unexpected value still renders sensibly instead
 * of falling through a switch. */
export type StockMovementType = 'Initial' | 'Adjustment' | 'Sale' | 'SaleReversal' | 'TransferOut' | 'TransferIn';

/** GET /api/stock/product/{productId}/movements - one immutable audit row.
 * QuantityDelta is signed (server-computed); there is no separate "resulting
 * quantity" field, so a running balance can only be derived, not displayed
 * authoritatively, unless movements are read in full chronological order. */
export interface StockMovementDto {
  id: string;
  productId: string;
  companyId: string;
  companyName: string;
  type: StockMovementType;
  quantityDelta: number;
  reason: string | null;
  checkoutItemId: string | null;
  relatedCompanyId: string | null;
  relatedCompanyName: string | null;
  transferCorrelationId: string | null;
  createdAt: string;
  createdBy: string | null;
}

/** POST /api/stock/product/{productId}/company/{companyId}/adjust - sets
 * stock to an ABSOLUTE quantity, not a delta; the server computes the delta
 * and records an Adjustment (or Initial, if no ProductStock row exists yet)
 * movement. Reason is mandatory (STOCK_ADJUSTMENT_REASON_REQUIRED). */
export interface StockAdjustRequest {
  quantity: number;
  reason: string;
}

/** POST /api/stock/transfers - one atomic transfer between two Companies,
 * recorded as a paired TransferOut/TransferIn movement. Never implement a
 * transfer as two separate adjust calls from the frontend. */
export interface StockTransferRequest {
  productId: string;
  fromCompanyId: string;
  toCompanyId: string;
  quantity: number;
}

export interface StockTransferResultDto {
  source: ProductStockDto;
  destination: ProductStockDto;
}
