import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { Button } from 'primeng/button';
import { Select } from 'primeng/select';
import { Tag } from 'primeng/tag';
import { Observable, catchError, finalize, forkJoin, of } from 'rxjs';
import { PagedResult } from '../../../../core/models/paged-result.model';
import { CommissionCalculationType, CommissionEntryDto, CommissionRuleDto, CommissionSubjectType, commissionEntryStatusSeverity } from '../../../../core/models/commission.model';
import { CurrentEmployeeService } from '../../../../core/services/current-employee.service';
import { CommissionsService } from '../../../../core/services/commissions.service';
import { EmployeesService } from '../../../../core/services/employees.service';
import { PackagesService } from '../../../../core/services/packages.service';
import { ProductsService } from '../../../../core/services/products.service';
import { ServicesService } from '../../../../core/services/services.service';
import { NotificationService } from '../../../../core/services/notification.service';
import { EurCurrencyPipe } from '../../../../shared/pipes/eur-currency.pipe';
import { HrDatePipe } from '../../../../shared/pipes/hr-date.pipe';
import { toDateOnly, toStartOfDayIso } from '../../../../core/utils/date.util';
import { translationReadySignal } from '../../../../core/utils/translation-signal.util';
import { addDays, dateFromLocalKey } from '../../../../shared/components/schedule-grid/schedule-date.util';
type Subject = { id: string; name: string; executionMode?: string };
@Component({ selector: 'app-admin-commissions', imports: [FormsModule, TranslatePipe, Button, Select, Tag, EurCurrencyPipe, HrDatePipe], templateUrl: './commissions.component.html', styleUrl: './commissions.component.scss' })
export class CommissionsComponent {
  private readonly api = inject(CommissionsService); private readonly employeesApi = inject(EmployeesService); private readonly servicesApi = inject(ServicesService); private readonly productsApi = inject(ProductsService); private readonly packagesApi = inject(PackagesService); private readonly notifications = inject(NotificationService); protected readonly currentEmployee = inject(CurrentEmployeeService); private readonly translate = inject(TranslateService); private readonly translationsReady = translationReadySignal(this.translate);
  protected readonly commissionEntryStatusSeverity = commissionEntryStatusSeverity;
  readonly subjectTypeOptions = computed(() => { this.translationsReady(); return this.subjectTypes.map(value => ({ value, label: this.translate.instant(`COMMISSIONS.SUBJECT_TYPE.${value}`) })); });
  readonly calculationTypeOptions = computed(() => { this.translationsReady(); return this.calculationTypes.map(value => ({ value, label: this.translate.instant(`COMMISSIONS.CALC_TYPE.${value}`) })); });
  readonly rules = signal<CommissionRuleDto[]>([]); readonly entries = signal<CommissionEntryDto[]>([]); readonly total = signal(0); readonly loading = signal(false); readonly failed = signal(false); readonly saving = signal(false); readonly employees = signal<Subject[]>([]); readonly services = signal<Subject[]>([]); readonly products = signal<Subject[]>([]); readonly packages = signal<Subject[]>([]);
  // Two separate fields: the history filter must never pre-fill (or be changed by) the new-rule form.
  selectedEmployeeId = ''; ruleEmployeeId = ''; selectedSubjectType: CommissionSubjectType = 'Service'; selectedSubjectId = ''; calculationType: CommissionCalculationType = 'Percentage'; value: number | null = null; from = this.dayOffset(-30); to = this.dayOffset(0); page = 1; readonly pageSize = 20; readonly subjectTypes: CommissionSubjectType[] = ['Service', 'Product', 'Package']; readonly calculationTypes: CommissionCalculationType[] = ['Percentage', 'Fixed'];
  constructor() { this.loadLookups(); this.refresh(); }
  get canManage(): boolean { return this.currentEmployee.can('commissions.manage'); } get subjects(): Subject[] { return this.selectedSubjectType === 'Service' ? this.services() : this.selectedSubjectType === 'Product' ? this.products() : this.packages(); } get groupService(): boolean { return this.selectedSubjectType === 'Service' && this.services().find(x => x.id === this.selectedSubjectId)?.executionMode === 'Group'; }
  subjectTypeChanged(): void { this.selectedSubjectId = ''; if (this.groupService) this.calculationType = 'Fixed'; }
  private refreshToken = 0;
  refresh(): void { const token = ++this.refreshToken; this.loading.set(true); this.failed.set(false); // Local business days; the backend filters EarnedAt >= from && EarnedAt < to, so `to` is the next local midnight.
    const from = toStartOfDayIso(dateFromLocalKey(this.from)); const to = toStartOfDayIso(addDays(dateFromLocalKey(this.to), 1)); const entries = this.api.getEntries({ employeeId: this.selectedEmployeeId || undefined, from, to, page: this.page, pageSize: this.pageSize }); const rules = this.canManage ? this.api.getRules({ employeeId: this.selectedEmployeeId || undefined }) : of<CommissionRuleDto[]>([]); forkJoin({ rules, entries }).pipe(finalize(() => { if (token === this.refreshToken) this.loading.set(false); })).subscribe({ next: ({rules, entries}) => { if (token !== this.refreshToken) return; this.rules.set(rules); this.entries.set(entries.items); this.total.set(entries.totalCount); }, error: () => { if (token !== this.refreshToken) return; this.rules.set([]); this.entries.set([]); this.total.set(0); this.failed.set(true); } }); }
  createRule(): void { if (!this.canManage) return; if (!this.ruleEmployeeId || !this.selectedSubjectId || this.value === null || this.value < 0 || (this.calculationType === 'Percentage' && this.value > 100)) { this.notifications.showWarning(this.translate.instant('COMMISSIONS.INVALID_RULE')); return; } const request = { employeeId: this.ruleEmployeeId, subjectType: this.selectedSubjectType, serviceId: this.selectedSubjectType === 'Service' ? this.selectedSubjectId : null, productId: this.selectedSubjectType === 'Product' ? this.selectedSubjectId : null, packageId: this.selectedSubjectType === 'Package' ? this.selectedSubjectId : null, calculationType: this.groupService ? 'Fixed' as const : this.calculationType, value: this.value }; this.saving.set(true); this.api.createRule(request).pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.value = null; this.notifications.showSuccess(this.translate.instant('COMMISSIONS.RULE_CREATED')); this.refresh(); }, error: () => {} }); }
  toggle(rule: CommissionRuleDto): void { const request = rule.isActive ? this.api.deactivateRule(rule.id) : this.api.activateRule(rule.id); this.saving.set(true); request.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.notifications.showSuccess(this.translate.instant(rule.isActive ? 'COMMISSIONS.RULE_DEACTIVATED' : 'COMMISSIONS.RULE_ACTIVATED')); this.refresh(); }, error: () => {} }); }
  subjectName(rule: CommissionRuleDto): string { return rule.serviceName ?? rule.productName ?? rule.packageName ?? '—'; } source(entry: CommissionEntryDto): string { return entry.appointmentId ? this.translate.instant('COMMISSIONS.SOURCE.APPOINTMENT', { id: entry.appointmentId }) : entry.checkoutItemId ? this.translate.instant('COMMISSIONS.SOURCE.CHECKOUT', { id: entry.checkoutItemId }) : entry.bookingId ? this.translate.instant('COMMISSIONS.SOURCE.BOOKING', { id: entry.bookingId }) : '—'; } previous(): void { if (this.page > 1) { this.page--; this.refresh(); } } next(): void { if (this.page * this.pageSize < this.total()) { this.page++; this.refresh(); } }
  // Each lookup degrades on its own: one 403 (e.g. no employees.view) must not blank the other pickers.
  private loadLookups(): void { const safe = <T>(page$: Observable<PagedResult<T>>) => page$.pipe(catchError(() => of<PagedResult<T>>({ items: [], totalCount: 0, page: 1, pageSize: 200 }))); forkJoin({ employees: safe(this.employeesApi.getPage({page:1,pageSize:200,isActive:true})), services: safe(this.servicesApi.getPage({page:1,pageSize:200,isActive:true})), products: safe(this.productsApi.getPage({page:1,pageSize:200,isActive:true})), packages: safe(this.packagesApi.getPage({page:1,pageSize:200,isActive:true})) }).subscribe(({employees,services,products,packages}) => { this.employees.set(employees.items.map(x => ({id:x.id,name:`${x.firstName} ${x.lastName}`}))); this.services.set(services.items.map(x => ({id:x.id,name:x.name,executionMode:x.executionMode}))); this.products.set(products.items.map(x => ({id:x.id,name:x.name}))); this.packages.set(packages.items.map(x => ({id:x.id,name:x.name}))); }); } /** Local calendar date (YYYY-MM-DD) `days` from today - toISOString() would give the UTC date. */
  private dayOffset(days: number): string { return toDateOnly(addDays(new Date(), days)); }
}
