import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Button } from 'primeng/button';
import { Select } from 'primeng/select';
import { Tag } from 'primeng/tag';
import { finalize, forkJoin, of } from 'rxjs';
import { CommissionCalculationType, CommissionEntryDto, CommissionRuleDto, CommissionSubjectType, commissionEntryStatusLabel, commissionEntryStatusSeverity } from '../../../../core/models/commission.model';
import { CurrentEmployeeService } from '../../../../core/services/current-employee.service';
import { CommissionsService } from '../../../../core/services/commissions.service';
import { EmployeesService } from '../../../../core/services/employees.service';
import { PackagesService } from '../../../../core/services/packages.service';
import { ProductsService } from '../../../../core/services/products.service';
import { ServicesService } from '../../../../core/services/services.service';
import { NotificationService } from '../../../../core/services/notification.service';
import { EurCurrencyPipe } from '../../../../shared/pipes/eur-currency.pipe';
import { HrDatePipe } from '../../../../shared/pipes/hr-date.pipe';
type Subject = { id: string; name: string; executionMode?: string };
@Component({ selector: 'app-admin-commissions', imports: [FormsModule, Button, Select, Tag, EurCurrencyPipe, HrDatePipe], templateUrl: './commissions.component.html', styleUrl: './commissions.component.scss' })
export class CommissionsComponent {
  private readonly api = inject(CommissionsService); private readonly employeesApi = inject(EmployeesService); private readonly servicesApi = inject(ServicesService); private readonly productsApi = inject(ProductsService); private readonly packagesApi = inject(PackagesService); private readonly notifications = inject(NotificationService); protected readonly currentEmployee = inject(CurrentEmployeeService);
  protected readonly commissionEntryStatusLabel = commissionEntryStatusLabel; protected readonly commissionEntryStatusSeverity = commissionEntryStatusSeverity;
  readonly rules = signal<CommissionRuleDto[]>([]); readonly entries = signal<CommissionEntryDto[]>([]); readonly total = signal(0); readonly loading = signal(false); readonly saving = signal(false); readonly employees = signal<Subject[]>([]); readonly services = signal<Subject[]>([]); readonly products = signal<Subject[]>([]); readonly packages = signal<Subject[]>([]);
  selectedEmployeeId = ''; selectedSubjectType: CommissionSubjectType = 'Service'; selectedSubjectId = ''; calculationType: CommissionCalculationType = 'Percentage'; value: number | null = null; from = this.dayOffset(-30); to = this.dayOffset(0); page = 1; readonly pageSize = 20; readonly subjectTypes: CommissionSubjectType[] = ['Service', 'Product', 'Package']; readonly calculationTypes: CommissionCalculationType[] = ['Percentage', 'Fixed'];
  constructor() { this.loadLookups(); this.refresh(); }
  get canManage(): boolean { return this.currentEmployee.can('commissions.manage'); } get subjects(): Subject[] { return this.selectedSubjectType === 'Service' ? this.services() : this.selectedSubjectType === 'Product' ? this.products() : this.packages(); } get groupService(): boolean { return this.selectedSubjectType === 'Service' && this.services().find(x => x.id === this.selectedSubjectId)?.executionMode === 'Group'; }
  subjectTypeChanged(): void { this.selectedSubjectId = ''; if (this.groupService) this.calculationType = 'Fixed'; }
  refresh(): void { this.loading.set(true); const from = `${this.from}T00:00:00.000Z`; const to = `${this.to}T23:59:59.999Z`; const entries = this.api.getEntries({ employeeId: this.selectedEmployeeId || undefined, from, to, page: this.page, pageSize: this.pageSize }); const rules = this.canManage ? this.api.getRules({ employeeId: this.selectedEmployeeId || undefined }) : of<CommissionRuleDto[]>([]); forkJoin({ rules, entries }).pipe(finalize(() => this.loading.set(false))).subscribe({ next: ({rules, entries}) => { this.rules.set(rules); this.entries.set(entries.items); this.total.set(entries.totalCount); }, error: () => { this.rules.set([]); this.entries.set([]); this.total.set(0); } }); }
  createRule(): void { if (!this.canManage || !this.selectedEmployeeId || !this.selectedSubjectId || this.value === null || this.value < 0 || (this.calculationType === 'Percentage' && this.value > 100)) return; const request = { employeeId: this.selectedEmployeeId, subjectType: this.selectedSubjectType, serviceId: this.selectedSubjectType === 'Service' ? this.selectedSubjectId : null, productId: this.selectedSubjectType === 'Product' ? this.selectedSubjectId : null, packageId: this.selectedSubjectType === 'Package' ? this.selectedSubjectId : null, calculationType: this.groupService ? 'Fixed' as const : this.calculationType, value: this.value }; this.saving.set(true); this.api.createRule(request).pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => { this.value = null; this.notifications.showSuccess('Pravilo provizije je spremljeno.'); this.refresh(); }, error: () => {} }); }
  toggle(rule: CommissionRuleDto): void { const request = rule.isActive ? this.api.deactivateRule(rule.id) : this.api.activateRule(rule.id); this.saving.set(true); request.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => this.refresh(), error: () => {} }); }
  subjectName(rule: CommissionRuleDto): string { return rule.serviceName ?? rule.productName ?? rule.packageName ?? '—'; } source(entry: CommissionEntryDto): string { return entry.appointmentId ? `Termin ${entry.appointmentId}` : entry.checkoutItemId ? `Blagajna ${entry.checkoutItemId}` : entry.bookingId ? `Rezervacija ${entry.bookingId}` : '—'; } previous(): void { if (this.page > 1) { this.page--; this.refresh(); } } next(): void { if (this.page * this.pageSize < this.total()) { this.page++; this.refresh(); } }
  private loadLookups(): void { forkJoin({ employees: this.employeesApi.getPage({page:1,pageSize:200,isActive:true}), services: this.servicesApi.getPage({page:1,pageSize:200,isActive:true}), products: this.productsApi.getPage({page:1,pageSize:200,isActive:true}), packages: this.packagesApi.getPage({page:1,pageSize:200,isActive:true}) }).subscribe(({employees,services,products,packages}) => { this.employees.set(employees.items.map(x => ({id:x.id,name:`${x.firstName} ${x.lastName}`}))); this.services.set(services.items.map(x => ({id:x.id,name:x.name,executionMode:x.executionMode}))); this.products.set(products.items.map(x => ({id:x.id,name:x.name}))); this.packages.set(packages.items.map(x => ({id:x.id,name:x.name}))); }); } private dayOffset(days: number): string { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString().slice(0,10); }
}
